### PR TITLE
Grafana: add new panel to indicate which env we are targeting.

### LINKED ISSUE #376: Update grafana dashboards to show environment info
**What**

- currently our grafana drop down is difficult to read. Using a label on the namespace rather than the namespace name should help us know which env we are targeting 
- We have labels on the controller deployment to indicate which env we are in

- [ ] add new panel with env info

### PR DESCRIPTION
**Pull request by ChristianZaccaria**
Closes #376

## Description of Changes
* Added new panel to Grafana to show which env we are in:
Screenshot from 2022-09-15 10-12-18

## Remaining Work 
* Found bug (unrelated to issue): when there is a gap in glbc_controller_reconcile_total metric at this point in time, the env in the dropdown is not shown.

### CODE REVIEW

**Review by maleck13 — APPROVED** [review]
changes look good to me. I think we can merge and check in the environment

**Comment by david-martin** [comment]
I meant to leave a comment on this to reflect an offline conversation.
The dashboard changes aren't reflecting well in the grafana version deployed locally (via kube-prometheus). This is down to a few things that Christian was going to look into.
- version differences of Grafana / plugins
- addition of the glbc_name label being absent locally
- kube-state-metrics not including all labels by default in the kube_pod_labels metric
- a way to specify the glbc_name label as an 'include' rather than having to 'exclude' a specific list of all other labels

It's OK that this is merged as it should work in our internal Openshift environment.
However, a follow up PR to address some of the remaining things can follow.

**Comment by ChristianZaccaria** [comment]
https://github.com/Kuadrant/kcp-glbc/issues/409

**Comment by ChristianZaccaria** [comment]
#409

**Pull request merged**
